### ISSUE TITLE
Deprecate Cosmid

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#100]
I think it's time :sweat_smile:

There's a new project to leverage conda to handle also genomic resources - why not?

https://github.com/gogetdata/ggd-recipes

**Comment by henrikstranneheim** [comment]
Awesome! Been waiting for approaches like that for some time. Will follow and implement when ready

Skickat från min iPhone

**Comment by henrikstranneheim** [comment]
Implementet own solution since I could not get gogetdat to work properly
