### ISSUE TITLE
Skip `conda update conda` in install script

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#102]
It seems that updating conda can have some weird side effects

Now it changed how the `source activate` script works between 4.0 and 4.1 which broke our setup

I think it would be nice to touch the environment as little as possible in the install script so perhaps consider removing this line :)

**Comment by henrikstranneheim** [comment]
Unexpected!  I will add add it as a option and set the default to not update!

**Comment by henrikstranneheim** [comment]
Done
