### ISSUE TITLE
Add support for SLURM's qos

### ISSUE THREAD

**Issue by ingkebil** [henrikstranneheim/MIP#107]
It would be nice to be able to specify a `qos`, `quality of service` to the slurm jobs.

See: http://slurm.schedmd.com/qos.html

This means to be able to add a `--qos <name>` to an sbatch. e.g. `sbatch --qos=low` to put the job into a low priority queue. This can be done by adding it to an sbatch script header, like such:
https://github.com/Clinical-Genomics/demultiplexing/blob/master/scripts/hiseqx/xdemuxtiles.batch#L6

**Comment by henrikstranneheim** [comment]
Added SLURM QOS to sbatch header

    - Allowed values: [low, normal, high]. Defaults to "normal"

change in config or on cmd using: '-qos/--slurmQualityofService'
