### ISSUE TITLE
Running MIP without affected individuals

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#108]
Hi,

I was running an analysis with two samples and none of them marked as affected

It seems that `genmod models` skips these "families" and outputs an empty VCF(?). Anyways it affects the next step in the PIPE in "VariantAnnotationBlock" and eventually the script fails.

Is there a way to tell MIP that you are not running with affected individuals to skip annotating genetic models? Or another way to skip for example the whole annotation step if you are just looking to generate variants and some statistics?

**Comment by henrikstranneheim** [comment]
Just skip the entire genmod step, :)
