### ISSUE TITLE
Chanjo 4 support

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#114]
Hi,

I hope it's not to late to fix a VERY tiny bug to enable us to switch to Chanjo 4

There's no more `-v` option - it's been replaced with `--log-level` and `--log_file` is now `--log-file`

That's all!

**Comment by robinandeer** [comment]
nu finns v4.0.0 på PIP snart också!

**Comment by henrikstranneheim** [comment]
Great!

Done!
