### ISSUE TITLE
Can't run single unaffected sample

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#119]
Hej,

MIP fails for a case with a single unaffected sample

I've tried to figure out why and it happens in the "sv_rankvariants" step.

The xargs command to "genmod annotate" splits up processing per chromosome but there is no merging happening before Picard is used to sort to resulting VCF.

That VCF is not found and the script crashes

I looked at another random trio and noticed that the xargs command to genmod doesn't process each chromosome individually and only yields one output - which works!

This is the script if you want to have a closer look:

/mnt/hds/proj/bioinfo/MIP_ANALYSIS/customers/cust005/PatientA/analysis/scripts/PatientA/bwa/sv_rankvariant_PatientA.0.sh

**Comment by henrikstranneheim** [comment]
Yes, there was an issue that arose when I switched the order of genmod annotate. I have modified the code and will run an exome test overnight.

**Comment by henrikstranneheim** [comment]
Fixed in master v4.0.4
