### ISSUE TITLE
Missing "bamstats" for Undetermined files

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#121]
Hi,

noticed that the "bamstats" section of qc metrics is missing from the Undetermined file pairs...

I remember you are treating them differently to avoid the analysis failing on low mapping etc. However it would be great to get the stats in the qc metrics output still, right?

**Comment by henrikstranneheim** [comment]
Yes, I see that could still be of value. I will make MIP process the Undetermined files as usual i.e. add them to qc_sampleInfo and then make qccollect let them by without evaluating them. 

Look forward to another hotfix...:)

**Comment by robinandeer** [comment]
Perfect!
Thanks

**Comment by henrikstranneheim** [comment]
Done in v.4.0.6
