### ISSUE TITLE
Start mixed analysis wes + wgs

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#122]
Hi,

when trying to start MIP with 3 wgs and 1 wes sample we get an error in the start script:

```
[FATAL] 2017/01/31 15:40:17 MIP_logger - Could not detect ELH2176A1 for '--exome_target_bed'. Provided sample_ids are: ELH2176A3
```

"ELH2176A3" is the only wes sample and it has a `capture_kit: Agilent_SureSelect.V5` reference in the pedigree file. "ELH2176A1" is a wgs sample tho so it should need a reference to a target bed file, right?

**Comment by henrikstranneheim** [comment]
All samples should have a capture kit. This is enforced to define the exome qc analyses even for wgs samples.

If you provide the capture kit for one sample MIP will require that you defined them for all samples - as you are supplying something different than the default and this need to be set for all samples.
If no capture kit is provided for any sample MIP will fall back to the "latest" capture kit and automatically set it for all samples as default. 

So either remove the wes capture kit - MIP will use the "latest" for all or supply capture kits for all.
