### ISSUE TITLE
manta error: unexpected read name collision

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#123]
Hi,

we are getting an error on many of the cases in Manta

I found an issue with the same manta error tho which suggests it has something to do with split reads notations: https://github.com/Illumina/manta/issues/49

Perhaps we need to upgrade bwa or add a `-M` flag to the `bwa mem` command :)

**Comment by robinandeer** [comment]
now I see you already use that flag..

**Comment by henrikstranneheim** [comment]
Problem seems to lie in duplicated fastq files. Nothing wrong with Manta or MIP.
