### ISSUE TITLE
Can't start unaffected sample

### ISSUE THREAD

**Issue by Dilea** [henrikstranneheim/MIP#125]
[WARN] 2017/02/13 16:40:38 MIP_logger - Only unaffected sample(s) in pedigree - skipping genmod 'models', 'score' and 'compound'
Can't use string ("") as a SCALAR ref while "strict refs" in use at /mnt/hds/proj/bioinfo/SERVER/miniconda/bin/mip.pl line 9095.

**Comment by henrikstranneheim** [comment]
Fixed in new hotfix merged to master
