### ISSUE TITLE
List Rank Models in documentation website

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#127]
Would it be helpful to upload the rank models for each version to the MIP documentation?

This way we can link to the in Scout and they can be shared with the community 👍

**Comment by henrikstranneheim** [comment]
Sure! 
Snv/Indels
v.1.18 is already there: http://mip-api.readthedocs.io/en/latest/rank_modelv1.18.html

SV
v1.0 is already there: http://mip-api.readthedocs.io/en/latest/svrank_modelv1.0.html

I think all samples have been analysed using these versions. I will make sure to add the new models as we update in the analysis.

**Comment by robinandeer** [comment]
Very cool - we'll add a link from Scout
