### ISSUE TITLE
genmod version in qc metrics

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#128]
Hej,

I've noticed that the genmod version isn't included in QC metrics for some reason

Is that expected or not? Is it only included in some analyses?

**Comment by henrikstranneheim** [comment]
No, I have to check that out.

Skickat från min iPhone

**Comment by henrikstranneheim** [comment]
@robinandeer Could you provide me with some case examples

**Comment by robinandeer** [comment]
This is an analysis where I don't see the genmod version:

`/mnt/hds/proj/bioinfo/housekeeper/analyses/cust003-17007/2017-02-08/17007_qc_metrics.mod.yaml`

**Comment by henrikstranneheim** [comment]
Also one needs to update qcregexp for this change to take effect
