### ISSUE TITLE
Incompatible command option

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#18]
Hi, I'm trying out the new ``-pythonVirtualEnvironmentCommand``-option. I would like to set the value to a string with two words "source activate". However it seems as if MIP doesn't parse this from the command line as expected.

```bash
-pythonVirtualEnvironment mip2.0 -pythonVirtualEnvironmentCommand source activate -pQCCollect 1
```

In the generated SBATCH files it prints  "source" and misses the second term "activate". Is there a workaround for this that I'm not aware of?

Simply adding quotation marks around the option in the YAML file will likely not help I guess.

**Comment by henrikstranneheim** [comment]
You can now supply arbitrarly long whitespace -pythonVirtualEnvironmentCommand on the cmd. And as an array in the config.yaml. Either as:
pythonVirtualEnvironmentCommand:
 - source activate 

or 

pythonVirtualEnvironmentCommand:
 - source
 - activate
