### ISSUE TITLE
YAML key unexpectadly integer

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#26]
For some reason when MIP is run with a family ID that happens to be an integer, the keys in the YAML output are marked as integers which is a little confusing when you are trying to read it.

Is it possible to enforce the keys to always be strings?

```yaml
{14049: {'SIB914A22': {'ExomeTargetBedInfileLists': ... }}}
```

**Comment by henrikstranneheim** [comment]
Fixed! All keys in the yaml that can be interpreted as number are forced into string by adding quotes.
