### ISSUE TITLE
AnalysisDate not set in QC sample info

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#27]
Hi,

running latest version of MIP (master). After running the pipeline and checking that "AnalysisRunStatus: Finished" I still don't have an "AnalysisDate" in my ``*_qc_sampleInfo.yaml`` file. When is the "AnalysisDate" supposed to be set? During "AnalysisRunStatus"?

I believe that I've rerun some step (perhaps MIP in dryRun mode) and this has added the date in there...

**Comment by robinandeer** [comment]
This is the only reference I can find to when "AnalysisDate" is touched:

```perl
if ($scriptParameter{'dryRunAll'} == 2) {

    $sampleInfo{ $scriptParameter{'familyID'} }{ $scriptParameter{'familyID'} }{'AnalysisDate'} = $dateTimeStamp;
}
```

Have I misunderstood that you aren't supposed to expect this field in the YAML file?

**Comment by henrikstranneheim** [comment]
That was a bug. It should be in the YAML file. It has been fixed in the latest hotfix.
