### ISSUE TITLE
QC collect error

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#28]
Hi, can you help me out with an error I haven't seen before?

From STDERR:
```
Argument "\x{6f}\x{74}..." isn't numeric in numeric eq (==) at /mnt/hds/proj/bioinfo/MIP_ANALYSIS/modules/MIP/qcCollect.pl line 512.
```

The line referred to is:

```
if ( ($$chanjoSexCheckGenderRef eq "female") && ($sampleInfoFile{$$familyIDRef}{$$sampleIDRef}{'Sex'} == 2) ) { #Female
```

And as for the chanjo output:

```
#X_coverage     Y_coverage      sex
7.01124753059   0.0720640965212 female
```

**Comment by robinandeer** [comment]
New information - this error occurs due to the fact that setting sex to "other" will crash this script. Perl is not able to compare a string with an int.

ping @henrikstranneheim

**Comment by henrikstranneheim** [comment]
Yes, I am aware of this. I will change this to accomodate both string and int comp. 

Skickat från min iPhone

**Comment by henrikstranneheim** [comment]
Fixed in v.2.3.4
