### ISSUE TITLE
Independent log files for all processes

### ISSUE THREAD

**Issue by ingkebil** [henrikstranneheim/MIP#35]
Now all invocations of programs through xargs or sent to one log file, which makes it really hard to determine which program specifically has produced an error. It creates really messy log files and makes it really time consuming to debug.

e.g. if a bash script like BAMCalibrationAndGTBlock_*.0.sh is created, it will send all output to 
..../MIP_ANALYSIS/cust00X/170/analysis/exomes/sampleid/bwa/info/BAMCalibrationAndGTBlock_*.std[err|out].txt

Which is horrible to read. Errors are not matched up to output and because xargs doesn't halt execution on errr, you mostly get regular output after an error occurred.

Any solution to this would be awesome :)

**Comment by henrikstranneheim** [comment]
I have changed the stderr logging for xargs to output per process using this format file.X.Y.Z.stderr.txt.
where
X = is the sbatch script version
Y = is the corresponding xargs command in ascending order within the sbatch script
Z = is the processes in ascending order for the corresponding xargs command

This will be included in an upcoming release.
