### ISSUE TITLE
Add spidex database annotation

### ISSUE THREAD

**Issue by henrikstranneheim** [henrikstranneheim/MIP#36]

**Comment by henrikstranneheim** [comment]
Update rank score model to include spidex annotation

**Comment by henrikstranneheim** [comment]
Needed to reformat database (removing chr and fixing header) and reindex using tabix. Genmod compatible?

**Comment by henrikstranneheim** [comment]
Putative outdata from genmod as vcf INFO field:
VCF record
Spidex=HGNC:Allele|Nm_Transcript>dpsi_zscore

And putative rank model
Rank model:
[Spidex]
field_separators = ,_:_|_>
data_type = float
category_aggregate = min
category = splicing
record_aggregate = max
value-z0 = -1<=dpsi_zscore<=1
value-z1 = -1>=dpsi_zscore>=1
value-z2 = -2>=dpsi_zscore>=2
score-z0 = 0
score-z1 = 3
score-z2 = 5

**Comment by moonso** [comment]
Fixed in rank score model 1.12

**Comment by henrikstranneheim** [comment]
Included and tested
