### ISSUE TITLE
ChanjoAnnotate flag in config-template seems to be defect

### ISSUE THREAD

**Issue by emmser** [henrikstranneheim/MIP#46]
In config file for Rats (CMMS_Rasta_Config.v1.0.yaml) the flag is named chanjoCalculateCutoff: but in mip.pl it should be chanjoAnnotateCutoff:

**Comment by henrikstranneheim** [comment]
Nicely spotted! Just change the flag into chanjoAnnotateCutoff in the config. I have added a test to find these cases in the future.
