### ISSUE TITLE
Make virtualenv optional?

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#60]
Our use case is to have a single default production environment which is always sourced. This environment also contains the other MIP dependencies which makes it very convenient to deploy.

But if we have to source another env we loose all these binaries - how can we use the already existing env to run MIP?

**Comment by henrikstranneheim** [comment]
I guess I can make the python env optional by the user. Then MIP would then trust that the user has solved this before starting MIP and just try to call the program in batch as is. 

On 20 Oct 2015, at 08:02, Robin Andeer <notifications@github.com> wrote:

> Our use case is to have a single default production environment which is always sourced. This environment also contains the other MIP dependencies which makes it very convenient to deploy.
> 
> But if we have to source another env we loose all these binaries - how can we use the already existing env to run MIP?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by robinandeer** [comment]
That would suit us very well I believe :)
