### ISSUE TITLE
Chanjo 3 support

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#75]
This is the general workflow for running Chanjo 3:

New dependencies:
- Sambamba

Deprecated steps:
- `build`

Annotating coverage:
```bash
$ chanjo -vv --log_file=chanjo.log sambamba --exon_bed=ccds.regions.bed --cov_treshold 10 --cov_treshold 20 alignment.bam > chanjo.output.bed 
```

The results can be directly uploaded to a chanjo database without first running build ^^

**Comment by robinandeer** [comment]
I've uploaded version `3.0.0` to PyPI as of today

**Comment by henrikstranneheim** [comment]
Great! I will look into it asap

Skickat från min iPhone

**Comment by henrikstranneheim** [comment]
Fixed changes for: chanjo sambamba

@robinandeer : Waiting for chanjo sexcheck reintroduction as a subcommand

**Comment by robinandeer** [comment]
Working on this now. It will not be very robust we've noticed - it's a good idea to still complement it with something checking heterozygosity on the X chromosome

**Comment by robinandeer** [comment]
robinandeer/chanjo#161

**Comment by robinandeer** [comment]
Updated Chanjo and release version 3.1.0 on PyPI

**Comment by henrikstranneheim** [comment]
Done
