### ISSUE TITLE
Gender Check based on all sources of gender information

### ISSUE THREAD

**Issue by emmser** [henrikstranneheim/MIP#76]
A gender check that uses Chanjo, Pedigree and Plink, and fails if any information differ. Nice to have them all in qc-metrics too.

**Comment by henrikstranneheim** [comment]
Needs upgrade to Plink-1,9.

TRIOS:
./plink --vcf /mnt/hds/proj/cust003/develop/analysis/exomes/118/bwa/gatk/118_sorted_smd_rreal_brecal_gvcf_vrecal_BOTH.vcf --out vcf_data_unsplit --chr 23-24
./plink --bfile vcf_data_unsplit --split-x b37 --make-bed --out vcf_data
cp test/.fam.bak vcf_data.fam 
./plink --bfile vcf_data --indep-pairphase 20000 2000 0.5 --chr 23-24
./plink --bfile vcf_data --extract plink.prune.in --make-bed --out ld_pruned_xy
./plink --bfile ld_pruned_xy --check-sex

SINGLE CASE MALE:
./plink --vcf /mnt/hds/proj/cust003/develop/analysis/genomes/15044/bwa/gatk/15044_sorted_pmd_rreal_brecal_gvcf_vrecal_BOTH.vcf --chr 23-24 --out vcf_data_unsplit
./plink --bfile vcf_data_unsplit --split-x b37 --make-bed --out vcf_data
cp test/.fam.15044 vcf_data.fam
./plink --bfile vcf_data --check-sex y-only

SINGLE CASE FEMALE
./plink --vcf /mnt/hds/proj/cust003/develop/analysis/genomes/15043/bwa/gatk/15043_sorted_pmd_rreal_brecal_gvcf_vrecal_BOTH.vcf --chr 23-24 --out vcf_data_unsplit
./plink --bfile vcf_data_unsplit --split-x b37 --make-bed --out vcf_data
cp test/.fam.15043 vcf_data.fam
./plink --bfile vcf_data --check-sex

Other combinations i.e. siblings, cousins or no founders:
Split family run individually and aggregate for qc.
