### ISSUE TITLE
Central log file

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#78]
Perhaps an idea to steal from the bcbio pipeline ^^

It has some very interesting use cases when it comes to tracking the analysis: https://github.com/guillermo-carrasco/bcbio-nextgen-monitor

How would you track the current status of an analysis right now? I can tell if an analysis succeeded but can I somehow tell if and where the analysis failed?

**Comment by henrikstranneheim** [comment]
Well yes. You would just use SLURM. Squeue, scontrol and sacc would pretty much give you all you need.

No need to invent the wheel I think.

/H

> On 11 Nov 2015, at 09:58, Robin Andeer <notifications@github.com> wrote:
> 
> Perhaps an idea to steal from the bcbio pipeline ^^
> 
> It has some very interesting use cases when it comes to tracking the analysis: https://github.com/guillermo-carrasco/bcbio-nextgen-monitor <https://github.com/guillermo-carrasco/bcbio-nextgen-monitor>
> How would you track the current status of an analysis right now? I can tell if an analysis succeeded but can I somehow tell if and where the analysis failed?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/henrikstranneheim/MIP/issues/78>.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se <mailto:henstr18@kth.se>
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna
