### ISSUE TITLE
Issue in VEP for chromosome Y

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#79]
We discovered a problem with VEP for a case on chromosome Y. This is the STDERR output:

`Can't use an undefined value as a symbol reference at /mnt/hds/proj/bioinfo/MIP_ANALYSIS/modules/ensembl-tools-release-81/scripts/variant_effect_predictor/variant_effect_predictor.pl line 2467, <GEN1> line 205.`

Do you recognize what it might be?

**Comment by henrikstranneheim** [comment]
Are there any variants on Y in the file?

Skickat från min iPhone

**Comment by henrikstranneheim** [comment]
@robinandeer Was this resolved?

**Comment by robinandeer** [comment]
Yeah, we've had a bit too many problems for me to remember :-P
Probably was a weird case
