### ISSUE TITLE
Weird variant call/ranking

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#80]
Doesn't this look a little odd?
Do you have any idea what might cause this?

![screen shot 2015-11-12 at 09 24 05](https://cloud.githubusercontent.com/assets/1220232/11113702/321df17a-891f-11e5-8d21-5e4a1e053db2.png)

EDIT: https://clinical-db.scilifelab.se:8083/cust000/15125/variants/06daf647da2e15ed22bf23d66e0b44da

**Comment by moonso** [comment]
Only thing I can think if is splitted variant, can you check the big VCF if there is a multicall on this position?

**Comment by robinandeer** [comment]
Det här är från gvcf:en

`17      40696233        rs86312 C       G,<NON_REF>     7338.77 .       DB;DP=213;MLEAC=2,0;MLEAF=1.00,0.00;MQ=60.00;MQ0=0      GT:AD:GQ:PL:SB  1/1:0,213,0:99:7367,639,0,7367,639,7367:0,0,94,119`

**Comment by moonso** [comment]
Då förstår jag ingenting...

**Comment by henrikstranneheim** [comment]
It is multi-allelic and does not have the second allele, so it does make sense:
17	40696233	rs86312	C	G,A	179457.28	PASS	AC=2,0;AF=1.00,0.00;AN=2;BaseQRankSum=2.93;DB;DP=5689;FS=0.529;InbreedingCoeff=-0.0606;MQ=60.00;MQ0=0;MQRankSum=-1.975e+00;POSITIVE_TRAIN_SITE;QD=31.57;ReadPosRankSum=1.83;SOR=0.766;VQSLOD=3.09;culprit=FS	GT:AD:GQ:PL	1/1:0,213,0:99:7367,639,0,7367,639,7367

VT should split this into ./. for the A allele.

**Comment by moonso** [comment]
Yes this was more like i expected.

**Comment by robinandeer** [comment]
Okey, trying to understand whats happening here :)

Which VCF should I have looked in?
Why does the variant show up with such a relatively high rank score?
How should the variant be interpreted when it shows up in Scout?
