### ISSUE TITLE
% Mapped reads in qc-metrics

### ISSUE THREAD

**Issue by emmser** [henrikstranneheim/MIP#81]
In qc-metrics add the % mapped reads from the total number of used reads.

**Comment by henrikstranneheim** [comment]
Added the "PCT_PF_READS_ALIGNED" to evaluation in qcCollect.

**Comment by henrikstranneheim** [comment]
Also included bamstats for each infile and calculates the percentage mapped reads for each file and relays this information to qcCollect and analysisRunStatus. This should make it evident if there is a contamination or poor sequencing quality.
