### ISSUE TITLE
MIP install and perlbrew

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#93]
This is just my own experience installing MIP on rasta. It didn't initially work with the automatic Perl install since it complained about multi-process libs etc.

However using this one line install of perl, perlbrew, and cpanm:

```
curl -k -L http://xrl.us/installperlnix | bash
```

... it worked to install modules without messing more with bash variables etc. Pretty sweet.

I did have to compile Faidx myself tho, following the steps here: https://github.com/Ensembl/faidx_xs

**Comment by henrikstranneheim** [comment]
I'll check it out.

You should try again from the develop branch it has been updated since you last tried it. The problem you mentioned has been solved.
