### ISSUE TITLE
bioconda version of VEP

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#99]
Do you think this will work in the automatic installer?

https://bioconda.github.io/recipes/variant-effect-predictor/README.html

**Comment by robinandeer** [comment]
Here are a few more additions:

**Plink(2)**
- https://anaconda.org/bioconda/plink2
- https://anaconda.org/biobuilds/plink

**VCFTools**
- https://anaconda.org/bioconda/vcftools

**Comment by henrikstranneheim** [comment]
Great!

Plink should work outof the box and probably vcfTools to. However, I am unsure about VEP. I do not know if the bioconda only installs the basic script and no cache or plugins. Will check it out though.

**Comment by robinandeer** [comment]
Here they have more information: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/variant-effect-predictor/post-link.sh

**Comment by robinandeer** [comment]
I also guess some of the package depend on Perl ^^

https://anaconda.org/bioconda/perl

**Comment by henrikstranneheim** [comment]
Judging from the post it just pulls down the VEP zip and unzips it. You still then have to run the installer yourself. Also I have had a lot of trouble with the conda perl and cpanm and running on the nodes. What we have works fine. I will leave VEP via bioconda for now and use the working SHELL installation we have.

**Comment by robinandeer** [comment]
I'll do a quick test on Allan but will revert to the official installer if I run into problems
